/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.HoaDonDAO;
import entity.HoaDon;
import entity.SanPham;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20086
 */
public class FormChoHoaDon extends javax.swing.JPanel {
    private HoaDon hoaDon;
    private static HoaDonDAO hoaDon_DAO = new HoaDonDAO();
    
    /**
     * Creates new form FormChoHoaDon
     */
    public FormChoHoaDon() {
        initComponents();
        designTable();
        tblDanhSachCho();
    }

    private void designTable(){
        tbl_danhSachCho.getTableHeader().setFont(new java.awt.Font("Calibri", 1, 14));
        tbl_danhSachCho.getTableHeader().setOpaque(false);
        tbl_danhSachCho.getTableHeader().setBackground(new Color(102, 102, 255));
        tbl_danhSachCho.getTableHeader().setForeground(Color.WHITE);
        tbl_danhSachCho.setDefaultEditor(Object.class, null); 
    }
    
    private static void clearTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbl_danhSachCho.getModel();
        dtm.setRowCount(0);
    }
    
    public static void tblDanhSachCho(){
        clearTable();
        
        String sdt = txt_soDienThoai.getText();
        ArrayList<HoaDon>listDanhSachCho = hoaDon_DAO.getHoaDonChoBySDT(sdt);
        DefaultTableModel dtm = (DefaultTableModel) tbl_danhSachCho.getModel();
        
        for(HoaDon hdc : listDanhSachCho){
            Object[] rowData = {hdc.getMaHoaDon(), hdc.getKhachHang().getHoVaTen(), hdc.getKhachHang().getSdt()};
            dtm.addRow(rowData);
        }
    }
    
    private void tiepTucThanhToanHandler(){
        if(tbl_danhSachCho.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn hoá đơn muốn tiếp tục thanh toán");
            return;
        }
        
        if(!QuanLyBanHang.listChiTietHoaDon.isEmpty()){
            JOptionPane.showMessageDialog(null, "Đang thanh toán, không chen ngang được ......");
            return;
        }
        
        QuanLyBanHang.thanhToanHangCho(hoaDon);
        QLBH.chuyenFormThanhToan();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhSachCho = new javax.swing.JTable();
        lbl_soDienThoai = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        btn_tiepTucThanhToan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        setMaximumSize(new java.awt.Dimension(1130, 773));
        setMinimumSize(new java.awt.Dimension(1130, 773));

        tbl_danhSachCho.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbl_danhSachCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Tên khách hàng", "Số điện thoại"
            }
        ));
        tbl_danhSachCho.setRowHeight(30);
        tbl_danhSachCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhSachChoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhSachCho);

        lbl_soDienThoai.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_soDienThoai.setText("Số điện thoại:");

        txt_soDienThoai.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_soDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soDienThoaiKeyReleased(evt);
            }
        });

        btn_tiepTucThanhToan.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_tiepTucThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cash_register.png"))); // NOI18N
        btn_tiepTucThanhToan.setText("Tiếp tục thanh toán");
        btn_tiepTucThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tiepTucThanhToanMouseClicked(evt);
            }
        });
        btn_tiepTucThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiepTucThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(btn_tiepTucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_soDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_soDienThoai)
                        .addComponent(btn_tiepTucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tiepTucThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tiepTucThanhToanMouseClicked
        // TODO add your handling code here:
        tiepTucThanhToanHandler();
    }//GEN-LAST:event_btn_tiepTucThanhToanMouseClicked

    private void tbl_danhSachChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhSachChoMouseClicked
        // TODO add your handling code here:
        hoaDon = hoaDon_DAO.getHoaDonById((String) tbl_danhSachCho.getValueAt(tbl_danhSachCho.getSelectedRow(), 0));
    }//GEN-LAST:event_tbl_danhSachChoMouseClicked

    private void txt_soDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soDienThoaiKeyReleased
        // TODO add your handling code here:
        tblDanhSachCho();
    }//GEN-LAST:event_txt_soDienThoaiKeyReleased

    private void btn_tiepTucThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiepTucThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tiepTucThanhToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tiepTucThanhToan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_soDienThoai;
    private static javax.swing.JTable tbl_danhSachCho;
    private static javax.swing.JTextField txt_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
