/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.HoaDonDAO;
import entity.HoaDon;
import entity.SanPham;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20086
 */
public class FormChiTietHoaDon extends javax.swing.JFrame {
    private SanPham sanPham;
    private ArrayList<HoaDon>listHoaDon;
    private HoaDonDAO hoaDon_DAO = new HoaDonDAO();
    
    /**
     * Creates new form FormChiTietHoaDon
     */
    public FormChiTietHoaDon(SanPham sanPham, ArrayList<HoaDon>listHoaDon) {
        initComponents();
        this.sanPham = sanPham;
        this.listHoaDon = listHoaDon;
        thongTinSanPham();
        tblDanhSachHoaDon();
        designTable();
    }

    private void thongTinSanPham(){
        lbl_chatLieuValue.setText(sanPham.getChatLieu().getChatLieu());
        lbl_kichThuocValue.setText(sanPham.getKichThuoc().getKichThuoc());
        lbl_loaiSanPhamValue.setText(sanPham.getPhanLoai().getLoaiSanPham());
        lbl_maSanPhamValue.setText(sanPham.getMaSP());
        lbl_mauSacValue.setText(sanPham.getMauSac().getMauSac());
        lbl_nhaCungCapValue.setText(sanPham.getNhaCungCap().getTenNhaCungCap());
        lbl_xuatXuValue.setText(sanPham.getXuatXu().getNoiXuatXu());
        lbl_tenSanPhamValue.setText(sanPham.getTenSP());
    }
    
    private void tblDanhSachHoaDon(){
        DefaultTableModel dtm = (DefaultTableModel) tbl_danhSachHoaDon.getModel();
        dtm.setRowCount(0);
        for(HoaDon hd : listHoaDon){
            int tongTien = hoaDon_DAO.tongTienSanPhamThuocHoaDon(hd.getMaHoaDon(), sanPham.getMaSP());
            Object[] dataRow = {hd.getMaHoaDon(), hd.getNhanVien().getHoVaTen(), new SimpleDateFormat("dd/MM/yyyy").format(hd.getNgayLap()), 
                                NumberFormat.getInstance().format(tongTien)};
            dtm.addRow(dataRow);
        }
    }
    
        private void designTable() {
        tbl_danhSachHoaDon.getTableHeader().setFont(new java.awt.Font("Calibri", 1, 14));
        tbl_danhSachHoaDon.getTableHeader().setOpaque(false);
        tbl_danhSachHoaDon.getTableHeader().setBackground(new Color(102, 102, 255));
        tbl_danhSachHoaDon.getTableHeader().setForeground(Color.WHITE);
        tbl_danhSachHoaDon.setDefaultEditor(Object.class, null);
        tbl_danhSachHoaDon.setRowHeight(30);
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        sanPham_wrapper = new javax.swing.JPanel();
        lbl_maSanPham = new javax.swing.JLabel();
        lbl_maSanPhamValue = new javax.swing.JLabel();
        lbl_tenSanPham = new javax.swing.JLabel();
        lbl_tenSanPhamValue = new javax.swing.JLabel();
        lbl_nhaCungCap = new javax.swing.JLabel();
        lbl_nhaCungCapValue = new javax.swing.JLabel();
        lbl_xuatXu = new javax.swing.JLabel();
        lbl_xuatXuValue = new javax.swing.JLabel();
        lbl_mauSac = new javax.swing.JLabel();
        lbl_mauSacValue = new javax.swing.JLabel();
        lbl_kichThuoc = new javax.swing.JLabel();
        lbl_kichThuocValue = new javax.swing.JLabel();
        lbl_chatLieu = new javax.swing.JLabel();
        lbl_chatLieuValue = new javax.swing.JLabel();
        lbl_loaiSanPham = new javax.swing.JLabel();
        lbl_loaiSanPhamValue = new javax.swing.JLabel();
        hoaDon_wrapper = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhSachHoaDon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        title.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        title.setText("DANH SÁCH HOÁ ĐƠN CỦA SẢN PHẨM");

        sanPham_wrapper.setBackground(new java.awt.Color(255, 255, 255));
        sanPham_wrapper.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        lbl_maSanPham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_maSanPham.setText("Mã sản phẩm:");

        lbl_maSanPhamValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_maSanPhamValue.setText("Value");

        lbl_tenSanPham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_tenSanPham.setText("Tên sản phẩm:");

        lbl_tenSanPhamValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_tenSanPhamValue.setText("Value");

        lbl_nhaCungCap.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_nhaCungCap.setText("Nhà cung cấp:");

        lbl_nhaCungCapValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_nhaCungCapValue.setText("Value");

        lbl_xuatXu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_xuatXu.setText("Xuất xứ:");

        lbl_xuatXuValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_xuatXuValue.setText("Value");

        lbl_mauSac.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_mauSac.setText("Màu sắc:");

        lbl_mauSacValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_mauSacValue.setText("Value");

        lbl_kichThuoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_kichThuoc.setText("Kích thước:");

        lbl_kichThuocValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_kichThuocValue.setText("Value");

        lbl_chatLieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_chatLieu.setText("Chất liệu:");

        lbl_chatLieuValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_chatLieuValue.setText("Value");

        lbl_loaiSanPham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lbl_loaiSanPham.setText("Loại sản phẩm:");

        lbl_loaiSanPhamValue.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl_loaiSanPhamValue.setText("Value");

        javax.swing.GroupLayout sanPham_wrapperLayout = new javax.swing.GroupLayout(sanPham_wrapper);
        sanPham_wrapper.setLayout(sanPham_wrapperLayout);
        sanPham_wrapperLayout.setHorizontalGroup(
            sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addComponent(lbl_maSanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nhaCungCap)
                            .addComponent(lbl_xuatXu)
                            .addComponent(lbl_tenSanPham))
                        .addGap(20, 20, 20)
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nhaCungCapValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_maSanPhamValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52))
                            .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_tenSanPhamValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                    .addComponent(lbl_xuatXuValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_kichThuoc)
                    .addComponent(lbl_mauSac)
                    .addComponent(lbl_chatLieu)
                    .addComponent(lbl_loaiSanPham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addComponent(lbl_loaiSanPhamValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sanPham_wrapperLayout.createSequentialGroup()
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_chatLieuValue, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_kichThuocValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(lbl_mauSacValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        sanPham_wrapperLayout.setVerticalGroup(
            sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addComponent(lbl_mauSac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_kichThuoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_chatLieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_loaiSanPham))
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addComponent(lbl_mauSacValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_kichThuocValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nhaCungCap)
                            .addComponent(lbl_chatLieuValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_xuatXu)
                            .addComponent(lbl_loaiSanPhamValue)))
                    .addGroup(sanPham_wrapperLayout.createSequentialGroup()
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_maSanPham)
                            .addComponent(lbl_maSanPhamValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sanPham_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sanPham_wrapperLayout.createSequentialGroup()
                                .addComponent(lbl_tenSanPhamValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_nhaCungCapValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_xuatXuValue))
                            .addComponent(lbl_tenSanPham))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hoaDon_wrapper.setBackground(new java.awt.Color(255, 255, 255));
        hoaDon_wrapper.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14))); // NOI18N

        tbl_danhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Nhân viên phụ trách", "Ngày lập", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tbl_danhSachHoaDon);

        javax.swing.GroupLayout hoaDon_wrapperLayout = new javax.swing.GroupLayout(hoaDon_wrapper);
        hoaDon_wrapper.setLayout(hoaDon_wrapperLayout);
        hoaDon_wrapperLayout.setHorizontalGroup(
            hoaDon_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDon_wrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        hoaDon_wrapperLayout.setVerticalGroup(
            hoaDon_wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDon_wrapperLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel1.setText("    X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(hoaDon_wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(title)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(sanPham_wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sanPham_wrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoaDon_wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel hoaDon_wrapper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_chatLieu;
    private javax.swing.JLabel lbl_chatLieuValue;
    private javax.swing.JLabel lbl_kichThuoc;
    private javax.swing.JLabel lbl_kichThuocValue;
    private javax.swing.JLabel lbl_loaiSanPham;
    private javax.swing.JLabel lbl_loaiSanPhamValue;
    private javax.swing.JLabel lbl_maSanPham;
    private javax.swing.JLabel lbl_maSanPhamValue;
    private javax.swing.JLabel lbl_mauSac;
    private javax.swing.JLabel lbl_mauSacValue;
    private javax.swing.JLabel lbl_nhaCungCap;
    private javax.swing.JLabel lbl_nhaCungCapValue;
    private javax.swing.JLabel lbl_tenSanPham;
    private javax.swing.JLabel lbl_tenSanPhamValue;
    private javax.swing.JLabel lbl_xuatXu;
    private javax.swing.JLabel lbl_xuatXuValue;
    private javax.swing.JPanel sanPham_wrapper;
    private javax.swing.JTable tbl_danhSachHoaDon;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
