
package gui;

import dao.TaiKhoanDAO;
import entity.NhanVien;
import entity.TaiKhoan;
import static gui.FormDangNhap.nhanVien;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class FormTaoTaiKhoan extends javax.swing.JFrame {
 private static NhanVien nhanVien;
    private TaiKhoanDAO taiKhoan_DAO;
    /**
     * Creates new form FormTaoTaiKhoan
     */
    public FormTaoTaiKhoan(NhanVien nhanVien) {
      
        initComponents();
        TaiKhoan tk = new TaiKhoan();
        System.out.println(nhanVien);
         txt_TenTK.setText(tk.auto_ID());
          this.nhanVien = nhanVien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        lbl_TenTK = new javax.swing.JLabel();
        txt_TenTK = new javax.swing.JTextField();
        lbl_Pass = new javax.swing.JLabel();
        txt_Pass = new javax.swing.JPasswordField();
        lbl_PassConfirm = new javax.swing.JLabel();
        txt_PassConfirm = new javax.swing.JPasswordField();
        btn_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Tạo tài khoản");
        getContentPane().add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 380, 30));

        lbl_TenTK.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_TenTK.setText("Tên Tài Khoản");
        getContentPane().add(lbl_TenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_TenTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_TenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 62, 300, 30));

        lbl_Pass.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_Pass.setText("Mật Khẩu");
        getContentPane().add(lbl_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_Pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, 300, 30));

        lbl_PassConfirm.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_PassConfirm.setText("Nhập lại mật khẩu");
        getContentPane().add(lbl_PassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_PassConfirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txt_PassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 162, 300, 30));

        btn_register.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons-add.png"))); // NOI18N
        btn_register.setText("Tạo tài khoản");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        TaiKhoan tk = new TaiKhoan();
       
        char[] pass_Char = txt_Pass.getPassword();
        String pass = new String(pass_Char);
        char[] passConfirm_Char = txt_PassConfirm.getPassword();
        String passConfirm = new String(passConfirm_Char);
        if(!pass.equalsIgnoreCase(passConfirm))
        {
            JOptionPane.showMessageDialog(null, "Mật khẩu không trùng khớp");
            return;
        }
        tk.setTenTaiKhoan(txt_TenTK.getText());
        tk.setMatKhau(pass);
        tk.setLoaiTaiKhoan(false);
        tk.setNhanVien(nhanVien);
        System.out.println(tk);
        taiKhoan_DAO = new TaiKhoanDAO();
        if(taiKhoan_DAO.addTaiKhoan(tk) > 0){
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_Pass;
    private javax.swing.JLabel lbl_PassConfirm;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JPasswordField txt_PassConfirm;
    private javax.swing.JTextField txt_TenTK;
    // End of variables declaration//GEN-END:variables
}
