/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author 20086
 */
public class QuanLySanPham extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySanPham
     */
    public QuanLySanPham() {
        initComponents();
        addTabbedPane();
    }

    private void addTabbedPane(){
        tabbedPane.add("Thông tin chi tiết",new FormSanPham());
        tabbedPane.add("Thuộc tính sản phẩm", new FormThuocTinhSanPham());
        tabbedPane.add("Khuyến mãi", new FormKhuyenMai());
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1130, 773));
        setMinimumSize(new java.awt.Dimension(1130, 773));
        setPreferredSize(new java.awt.Dimension(1130, 773));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        tabbedPane.setMaximumSize(new java.awt.Dimension(1130, 775));
        tabbedPane.setMinimumSize(new java.awt.Dimension(1130, 775));
        tabbedPane.setPreferredSize(new java.awt.Dimension(1130, 775));
        add(tabbedPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
